##1. 파이썬의 입력과 출력

In [1]:
print('Hello world')

Hello world


In [2]:
print('Python을 시작합니다.\n안녕하세요?')

Python을 시작합니다.
안녕하세요?


In [3]:
pi=3.1415926545
print(pi)

3.1415926545


In [4]:
hello='안녕하세요'
print(hello)

안녕하세요


In [5]:
pi=3.1415926545
print('원주율이 {a}이고, 근사치로는 {b:.2f}입니다.'.format(a=pi, b=pi))

원주율이 3.1415926545이고, 근사치로는 3.14입니다.


In [6]:
name='멀티캠퍼스'
print('학원 이름은 {}입니다.'.format(name))

학원 이름은 멀티캠퍼스입니다.


## 2. 데이터의 유형과 처리

In [31]:
# 숫자

In [7]:
type(10)

int

In [8]:
type(3.14)

float

In [10]:
type(7+5j)

complex

In [ ]:
# 문자열

In [11]:
c3='Life'
c4='is'
c5='too'
c6='short'
c7=c3+c4+c5+c6
c8=c3+' '+c4+' '+c5+' '+c6
print(c7)
print(c8)

Lifeistooshort
Life is too short


In [14]:
c1='HELLO PYTHON'
c2='안녕하세요 파이썬씨? 우리 잘 해봅시다'

print(c1[0])
print(c1[-2])
print(c2[2])
print(c2[-3])

H
O
하
봅


In [15]:
c2='어서와 파이썬은 처음이지? 나도 처음이야'

print(c2[7])
print(c2[4:7])
print(c2[:6])
print(c2[-6:])

은
파이썬
어서와 파이
도 처음이야


In [16]:
print(c2.index('와'))
print(c2.find('파'))

2
4


In [18]:
c1='HELLO PYTHON'
c6='short'

print(c1.lower())
print(c6.upper())

hello python
SHORT


In [19]:
c9=' HELLO '
print(c9.lstrip())
print(c9.rstrip())
print(c9.strip())

HELLO 
 HELLO
HELLO


In [20]:
c10='멀티:캠퍼스'
print(c10.split(':'))

['멀티', '캠퍼스']


In [ ]:
# 목록(list)과 튜플(tuple)

In [21]:
a1 = [1,2,3,4]
a2 = ['Life','is','too','short']
a3=[1,2,'Python']
a4=[1,2,['Life','Python']]

print(a1[0])
print(a1[1]+a1[3])
print(a4[-1])
print(a4[-1][0])

1
6
['Life', 'Python']
Life


In [22]:
a1 = [1,2,3,4]
a2 = [4,5,6,7]
print(a1+a2)
print(a1*3)

[1, 2, 3, 4, 4, 5, 6, 7]
[1, 2, 3, 4, 1, 2, 3, 4, 1, 2, 3, 4]


In [24]:
a7=['a','b','c','d','e','f']
a7.append('g')
print(a7)

['a', 'b', 'c', 'd', 'e', 'f', 'g']


In [25]:
a8=[1,3,2,4,5,7,8,10,6]
a8.insert(2,9)
print(a8)

[1, 3, 9, 2, 4, 5, 7, 8, 10, 6]


In [26]:
a10=[1,2,3,4,5]
a11=[6,7,8,9,10]
a10.extend(a11)
print(a10)

[1, 2, 3, 4, 5, 6, 7, 8, 9, 10]


In [27]:
a10=[1,2,3,4,5]
a11=[6,7,8,9,10]
a10+=a11
print(a10)

[1, 2, 3, 4, 5, 6, 7, 8, 9, 10]


In [28]:
a6=[1,2,4,3,5,7,7,8]
a6[5] = 6
print(a6)

[1, 2, 4, 3, 5, 6, 7, 8]


In [29]:
a6=[1,2,4,3,5,7,7,8]
a6[2:4] = [3,4]
print(a6)

[1, 2, 3, 4, 5, 7, 7, 8]


In [30]:
a6=[1,2,4,3,5,7,7,8]
del a6[7]
print(a6)

[1, 2, 4, 3, 5, 7, 7]


In [34]:
a6=[1,2,4,3,5,7,7,8]
a6.pop(7)
print(a6)
a6.pop()
print(a6)

[1, 2, 4, 3, 5, 7, 7]
[1, 2, 4, 3, 5, 7]


In [35]:
a8=[1,3,2,4,5,7,8,10,6]
a8.sort()
print(a8)

[1, 2, 3, 4, 5, 6, 7, 8, 10]


In [36]:
a8=[1,3,2,4,5,7,8,10,6]
a8.sort(reverse=True)
print(a8)

[10, 8, 7, 6, 5, 4, 3, 2, 1]


In [38]:
a8=[1,3,2,4,5,7,8,10,6]
a8.reverse()
print(a8)

[6, 10, 8, 7, 5, 4, 2, 3, 1]


In [39]:
t1=(1,2,3,4,5)
t2=('a','b','c','d','e')
a1=['a','b','c','d','e']

print(type(t1))
print(type(t2))
print(type(a1))

<class 'tuple'>
<class 'tuple'>
<class 'list'>


In [ ]:
# 사전(dictionary)

In [40]:
d1={'name':'KIM', 'birth':2003, 'height':175}
print(d1['name'])

KIM


In [41]:
d1['weight']=60
print(d1)

{'name': 'KIM', 'birth': 2003, 'height': 175, 'weight': 60}


In [42]:
d1['height']=180
print(d1)

{'name': 'KIM', 'birth': 2003, 'height': 180, 'weight': 60}


In [43]:
del d1['name']
print(d1)

{'birth': 2003, 'height': 180, 'weight': 60}


In [44]:
d1key=list(d1.keys())
print(d1key)

['birth', 'height', 'weight']


In [45]:
d1value=list(d1.values())
print(d1value)

[2003, 180, 60]


In [46]:
print('number' in d1)
print('weight' in d1)

False
True


In [ ]:
# 다차원 배열(ndarray)

In [47]:
import numpy as np

In [48]:
v1=np.array([1,2,3,4])
print(v1)

[1 2 3 4]


In [49]:
v1=np.arange(5)
print(v1)

[0 1 2 3 4]


In [51]:
v4=np.arange(1,10,2)
print(v4)

[1 3 5 7 9]


In [52]:
v4=np.arange(1,10,2)*2
print(v4)

[ 2  6 10 14 18]


In [54]:
v5=np.arange(1,10,2)**3
print(v5)

[  1  27 125 343 729]


In [55]:
v2=np.arange(3,10,2, dtype=int)
print(v2)

[3 5 7 9]


In [56]:
v2=np.arange(3,10,2)
print(v2)

[3 5 7 9]


In [57]:
v3=np.arange(3.5,10,2, dtype=float)
print(v3)

[3.5 5.5 7.5 9.5]


In [58]:
v1=np.arange(12)
v2=v1.reshape(2,6)
v3=v1.reshape(2,6, order='F')
print(v1)
print(v2)
print(v3)

[ 0  1  2  3  4  5  6  7  8  9 10 11]
[[ 0  1  2  3  4  5]
 [ 6  7  8  9 10 11]]
[[ 0  2  4  6  8 10]
 [ 1  3  5  7  9 11]]


In [60]:
v1=np.arange(1,5).reshape(2,2)
print(v1)

[[1 2]
 [3 4]]


In [61]:
print(v1*v1)

[[ 1  4]
 [ 9 16]]


In [62]:
v1

array([[1, 2],
       [3, 4]])

In [63]:
print(np.dot(v1,v1))

[[ 7 10]
 [15 22]]


In [65]:
v3=np.arange(3.5, 10.5, 2, dtype=float)
v6=np.arange(1,5).reshape(2,2)

print(np.amax(v3))
print(np.amin(v6))
print(v3.dtype)
print(v6.shape)

9.5
1
float64
(2, 2)


In [67]:
m1=np.matrix([[1,2],[3,4]])
print(m1)
print(m1*m1)

[[1 2]
 [3 4]]
[[ 7 10]
 [15 22]]


## 3. 제어문

In [ ]:
# 조건문(if)

In [68]:
금액=5000
if 금액==5000:
    print('자장면')

자장면


In [69]:
금액=6000

if 금액==5000:
    print('자장면')
if 10000 > 금액 > 5000:
    print('짬뽕')

짬뽕


In [70]:
if 금액==5000:
    print('자장면')
elif 10000 > 금액 > 5000:
    print('짬뽕')

짬뽕


In [71]:
금액=4000

if 금액==5000:
    print('자장면')
elif 10000 > 금액 > 5000:
    print('짬뽕')
else:
    print('죄송해요')

죄송해요


In [72]:
음식메뉴=['자장면','짬뽕']

if '자장면' in 음식메뉴:
    print('자장면 이요.')
    
if '짬뽕' in 음식메뉴:
    print('짬뽕 이요.')
else:
    print('오늘 굶으세요')

자장면 이요.
짬뽕 이요.


In [73]:
if '자장면' in 음식메뉴:
    print('자장면 이요.')    
elif '짬뽕' in 음식메뉴:
    print('짬뽕 이요.')
else:
    print('오늘 굶으세요')

자장면 이요.


In [75]:
del 음식메뉴[0]
print(음식메뉴)

['짬뽕']


In [76]:
if '자장면' in 음식메뉴:
    print('자장면 이요.')    
elif '짬뽕' in 음식메뉴:
    print('짬뽕 이요.')
else:
    print('오늘 굶으세요')

짬뽕 이요.


In [77]:
del 음식메뉴[0]
print(음식메뉴)

[]


In [78]:
if '자장면' in 음식메뉴:
    print('자장면 이요.')    
elif '짬뽕' in 음식메뉴:
    print('짬뽕 이요.')
else:
    print('오늘 굶으세요')

오늘 굶으세요


In [81]:
음식메뉴.append('군만두')
print(음식메뉴)

['군만두']


In [82]:
if '자장면' in 음식메뉴:
    print('자장면 이요.')    
elif '짬뽕' in 음식메뉴:
    print('짬뽕 이요.')
else:
    print('오늘 굶으세요')

오늘 굶으세요


In [83]:
# 반복문(for)

In [84]:
for i in ['자장면','짬뽕', '군만두']:
    print(i)

자장면
짬뽕
군만두


In [85]:
음식메뉴 = ['자장면','짬뽕', '군만두']
for i in 음식메뉴:
    print(i)

자장면
짬뽕
군만두


In [86]:
for i in range(2,6):
    for j in range(1,5):
        print('{}+{}={}'.format(i,j,i*j), end=' ')
    print("")

2+1=2 2+2=4 2+3=6 2+4=8 
3+1=3 3+2=6 3+3=9 3+4=12 
4+1=4 4+2=8 4+3=12 4+4=16 
5+1=5 5+2=10 5+3=15 5+4=20 


In [87]:
중국음식 = ['자장면','짬뽕', '군만두','탕수육','팔보채']
for 메뉴 in 중국음식:
    if '자장면' in 메뉴:
        continue
    print(메뉴)

짬뽕
군만두
탕수육
팔보채


In [88]:
for 메뉴 in 중국음식:
    if '자장면' in 메뉴:
        pass
    print(메뉴)

자장면
짬뽕
군만두
탕수육
팔보채
