In [1]:
import pandas as pd

In [3]:
a={'a':10,'b':20, 'c':30,'d':40,'e':50}

In [4]:
type(a)

dict

In [5]:
b = pd.Series(a)

In [6]:
b

a    10
b    20
c    30
d    40
e    50
dtype: int64

In [7]:
type(b)

pandas.core.series.Series

In [8]:
b.shape

(5,)

In [10]:
import numpy as np

In [12]:
aa = np.arange(3,10)

In [13]:
aa

array([3, 4, 5, 6, 7, 8, 9])

In [14]:
bb= pd.Series(aa)

In [15]:
bb

0    3
1    4
2    5
3    6
4    7
5    8
6    9
dtype: int32

In [16]:
a

{'a': 10, 'b': 20, 'c': 30, 'd': 40, 'e': 50}

In [17]:
a.keys()

dict_keys(['a', 'b', 'c', 'd', 'e'])

In [18]:
a.values()

dict_values([10, 20, 30, 40, 50])

In [19]:
b

a    10
b    20
c    30
d    40
e    50
dtype: int64

In [20]:
b.index

Index(['a', 'b', 'c', 'd', 'e'], dtype='object')

In [21]:
b.values

array([10, 20, 30, 40, 50], dtype=int64)

In [22]:
c=[10,20,30,40,50]

In [23]:
d=pd.Series(c)

In [24]:
d

0    10
1    20
2    30
3    40
4    50
dtype: int64

In [25]:
type(d)

pandas.core.series.Series

In [26]:
d.shape

(5,)

In [27]:
d.index

RangeIndex(start=0, stop=5, step=1)

In [28]:
d.values

array([10, 20, 30, 40, 50], dtype=int64)

In [29]:
e=['a','b','c','d','e']

In [30]:
f = [10,20,30,40,50]

In [31]:
g= pd.Series(f,index=e)

In [32]:
g

a    10
b    20
c    30
d    40
e    50
dtype: int64

In [33]:
g.index

Index(['a', 'b', 'c', 'd', 'e'], dtype='object')

In [34]:
g.values

array([10, 20, 30, 40, 50], dtype=int64)

In [35]:
g['a']

10

In [36]:
g[2]

30

In [37]:
g['a':'d']

a    10
b    20
c    30
d    40
dtype: int64

In [38]:
g[0:4]

a    10
b    20
c    30
d    40
dtype: int64