In [2]:
import numpy as np

In [4]:
a=[10,20,30,40,50]

In [5]:
type(a)

list

In [6]:
b=np.array(a)

In [7]:
b

array([10, 20, 30, 40, 50])

In [8]:
print(b)

[10 20 30 40 50]


In [10]:
b.shape

(5,)

In [11]:
c=np.array([5,4,3,2,1])

In [12]:
c

array([5, 4, 3, 2, 1])

In [13]:
b+c

array([15, 24, 33, 42, 51])

In [14]:
b+5

array([15, 25, 35, 45, 55])

In [15]:
a+[5,4,3,2,1]

[10, 20, 30, 40, 50, 5, 4, 3, 2, 1]

In [16]:
np.sum(b)

150

In [17]:
b

array([10, 20, 30, 40, 50])

In [19]:
np.mean(b) #b.mean()

30.0

In [20]:
np.max(b)  #b.max() 와 동일

50

In [21]:
np.min(b)  #b.min()

10

In [24]:
b.min()

10

In [25]:
b.mean()

30.0

In [26]:
a

[10, 20, 30, 40, 50]

In [27]:
b

array([10, 20, 30, 40, 50])

In [28]:
c

array([5, 4, 3, 2, 1])

In [29]:
c=b/3

In [30]:
c

array([ 3.33333333,  6.66666667, 10.        , 13.33333333, 16.66666667])

In [31]:
np.round(c,1)

array([ 3.3,  6.7, 10. , 13.3, 16.7])

In [32]:
c.round(3)

array([ 3.333,  6.667, 10.   , 13.333, 16.667])

In [33]:
c

array([ 3.33333333,  6.66666667, 10.        , 13.33333333, 16.66666667])

In [34]:
b

array([10, 20, 30, 40, 50])

In [35]:
b[0]

10

In [36]:
b[1:3]

array([20, 30])

In [37]:
b[-1]

50

In [38]:
b[2:]

array([30, 40, 50])

In [41]:
b[2:].sum()

120

In [42]:
np.sum(b[2:])

120

In [43]:
np.mean(b[2:])

40.0

In [44]:
b[2:].mean()

40.0

In [45]:
b[1]=200
b

array([ 10, 200,  30,  40,  50])

In [46]:
d=np.arange(5)

In [47]:
d

array([0, 1, 2, 3, 4])

In [48]:
e=np.arange(3,8)
e

array([3, 4, 5, 6, 7])

In [49]:
f=np.arange(3,8,2)

In [50]:
f

array([3, 5, 7])

In [51]:
g=np.zeros(5)

In [52]:
g

array([0., 0., 0., 0., 0.])

In [53]:
h=np.ones(5)

In [54]:
h

array([1., 1., 1., 1., 1.])

In [55]:
b

array([ 10, 200,  30,  40,  50])

In [56]:
bb=b

In [57]:
bb

array([ 10, 200,  30,  40,  50])

In [58]:
bb[0]=100

In [59]:
bb

array([100, 200,  30,  40,  50])

In [60]:
b

array([100, 200,  30,  40,  50])

In [74]:
bb=b.copy()

In [75]:
bb

array([100, 200, 200,  40,  50])

In [76]:
b

array([100, 200, 200,  40,  50])

In [77]:
b[2]=20
b

array([100, 200,  20,  40,  50])

In [78]:
bb

array([100, 200, 200,  40,  50])

In [80]:
b==bb

array([ True,  True, False,  True,  True])