In [1]:
import numpy as np

In [2]:
a=np.arange(1,15)

In [3]:
a

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [4]:
a > 10

array([False, False, False, False, False, False, False, False, False,
       False,  True,  True,  True,  True])

In [5]:
a == 5

array([False, False, False, False,  True, False, False, False, False,
       False, False, False, False, False])

In [6]:
a[a>5]

array([ 6,  7,  8,  9, 10, 11, 12, 13, 14])

In [7]:
a

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [8]:
a[a<5]=5

In [9]:
a

array([ 5,  5,  5,  5,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [10]:
a[a>10]=10

In [11]:
a

array([ 5,  5,  5,  5,  5,  6,  7,  8,  9, 10, 10, 10, 10, 10])