In [4]:
import numpy as np

In [6]:
a=np.array([[10,20,30,40],[50,60,70,80]])

In [7]:
a

array([[10, 20, 30, 40],
       [50, 60, 70, 80]])

In [8]:
a.shape

(2, 4)

In [9]:
b,c=a.shape

In [10]:
b

2

In [11]:
c

4

In [12]:
np.mean(a)

45.0

In [13]:
a[1:].mean()

65.0

In [14]:
a[0].mean()

25.0

In [15]:
a[0,0]

10

In [16]:
a[-1,-1]

80

In [17]:
a[0,1:]

array([20, 30, 40])

In [18]:
a

array([[10, 20, 30, 40],
       [50, 60, 70, 80]])

In [19]:
a[0,1]=2

In [20]:
a

array([[10,  2, 30, 40],
       [50, 60, 70, 80]])

In [22]:
b=np.zeros((2,4))

In [23]:
b

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [24]:
c=np.ones((3,5))
c

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [27]:
c=np.arange(8)

In [28]:
type(c)

numpy.ndarray

In [29]:
c

array([0, 1, 2, 3, 4, 5, 6, 7])

In [30]:
c.reshape(2,4)

array([[0, 1, 2, 3],
       [4, 5, 6, 7]])

In [31]:
c.shape

(8,)

In [32]:
c=c.reshape(2,4)

In [33]:
c

array([[0, 1, 2, 3],
       [4, 5, 6, 7]])

In [34]:
c=c.T

In [35]:
c

array([[0, 4],
       [1, 5],
       [2, 6],
       [3, 7]])

In [36]:
c2=c.reshape(8)

In [37]:
c2

array([0, 4, 1, 5, 2, 6, 3, 7])

In [38]:
c2=c.T.reshape(8)

In [39]:
c2

array([0, 1, 2, 3, 4, 5, 6, 7])

In [40]:
c

array([[0, 4],
       [1, 5],
       [2, 6],
       [3, 7]])

In [41]:
c.sum()

28

In [42]:
np.sum(c)

28

In [43]:
d=c.copy()

In [44]:
d

array([[0, 4],
       [1, 5],
       [2, 6],
       [3, 7]])

In [45]:
d[0,0]=10
d

array([[10,  4],
       [ 1,  5],
       [ 2,  6],
       [ 3,  7]])

In [46]:
c

array([[0, 4],
       [1, 5],
       [2, 6],
       [3, 7]])

In [47]:
c ==d

array([[False,  True],
       [ True,  True],
       [ True,  True],
       [ True,  True]])

In [48]:
e=np.arange(49).reshape(7,7)

In [49]:
e

array([[ 0,  1,  2,  3,  4,  5,  6],
       [ 7,  8,  9, 10, 11, 12, 13],
       [14, 15, 16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25, 26, 27],
       [28, 29, 30, 31, 32, 33, 34],
       [35, 36, 37, 38, 39, 40, 41],
       [42, 43, 44, 45, 46, 47, 48]])

In [51]:
e[:,1:3]

array([[ 1,  2],
       [ 8,  9],
       [15, 16],
       [22, 23],
       [29, 30],
       [36, 37],
       [43, 44]])

In [53]:
e[3:,:4]

array([[21, 22, 23, 24],
       [28, 29, 30, 31],
       [35, 36, 37, 38],
       [42, 43, 44, 45]])

In [54]:
e[3:,:4].sum()

528

In [55]:
f=e[3:,:4].copy()
f

array([[21, 22, 23, 24],
       [28, 29, 30, 31],
       [35, 36, 37, 38],
       [42, 43, 44, 45]])

In [57]:
e[4,0]=100

In [58]:
e

array([[  0,   1,   2,   3,   4,   5,   6],
       [  7,   8,   9,  10,  11,  12,  13],
       [ 14,  15,  16,  17,  18,  19,  20],
       [ 21,  22,  23,  24,  25,  26,  27],
       [100,  29,  30,  31,  32,  33,  34],
       [ 35,  36,  37,  38,  39,  40,  41],
       [ 42,  43,  44,  45,  46,  47,  48]])

In [59]:
f

array([[21, 22, 23, 24],
       [28, 29, 30, 31],
       [35, 36, 37, 38],
       [42, 43, 44, 45]])

In [60]:
f.sum()

528